    ; ESCRIBIR UN PROGRAMA PARA LAMACENAR EL VALOR 33D EN 15 POSICIONES
    ; CONTIGUAS DE LA MEMORIA DE DATOS, EMPEZANDO EN LA DIRECCION 0x30
    
    LIST    P=16F887
    #INCLUDE	<P16F887.INC>
    
    VALOR   EQU	    0x21
    DIRIN   EQU	    0x30    
    CONT    EQU	    0x20
    
    ORG	    0x00
    GOTO    MAIN
    ORG	    0x05
    
MAIN
    ; DIRECCIONAMOS A BANK 0
    BCF	    STATUS,RP0
    BCF	    STATUS,RP1
    ; CARGO EL CONTANDO CON EL VALOR 15D
    MOVLW   0x0F
    MOVWF   CONT
    ; CARGAMOS EL REGISTRO FSR CON LA DIRRECION 0x30
    MOVLW   DIRIN
    MOVWF   FSR
    MOVLW   VALOR

LOOP
    
    MOVWF   INDF
    INCF    FSR
    DECFSZ  CONT
    GOTO    LOOP
    
    END
    