    ; ESCRIBIR UN PROGRAMA QUE PRENDA UN LED QUE SE VA DESPLAZANDO CADA
    ; VEZ QUE SE PULSA LA TECLA CONECTADA A RB0. AL PULSAR POR PRIMERA VEZ
    ; LA TECLA SE ENCIENDE EL LED CONECTADO A RB1 Y AL LLEGAR A RB3 VUELVE A 
    ; RB1 Y ASI INDEFINIDAMENTE. EL PROGRAMA PRINCIPAL NO REALIZA TAREA ALGUNA
    ; Y TODO SE DESARROLLA DENTRO DE LA SUBRUTINA DE INTERRUPCION.
    
    LIST	P=16F887
    #INCLUDE	<P16F887.INC>
    
    ; CONFIG1
; __config 0x3FF4
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
 
    CONT	EQU	0x20
    T1		EQU	0x21 
    T2		EQU	0x22
    
    ORG	    0x00
    GOTO    MAIN
    ORG	    0x04
    GOTO    ISR
    ORG	    0x05
    
MAIN
    ; CONFIGURO EL PUERTO B
    BANKSEL TRISB
    BSF	    TRISB,0	; CONFIGURO COMO INPUT RB0
    BANKSEL ANSELH
    CLRF    ANSELH
    BANKSEL PORTB
    CLRF    PORTB
    CLRF    CONT	; BORRO EL CONTADOR
    BANKSEL IOCB
    BSF	    IOCB,0
    
    ; CONFIGURO INTCON
    BSF	    INTCON,3
    
    BANKSEL OPTION_REG
    BCF	    OPTION_REG,7
    BSF	    INTCON,7
    GOTO    $
    
ISR
    MOVWF   0x23		; GUARDO EL CONTEXTO
    MOVF    STATUS,W
    MOVWF   0x24
    ; FIN DE GUARDADO DE CONTEXTO
    
    BANKSEL PORTB
    CALL    DELAY
    INCF    CONT
    MOVLW   0x01
    BTFSC   CONT,3	; CUANDO LLEGUE A 4 RESETEA
    MOVWF   CONT
    MOVF    CONT,W
    CALL    LED
    MOVWF   PORTB
VOLVER    
    BTFSS   PORTB,0
    GOTO    VOLVER
    
    ; RECUPERO EL CONTEXTO
    MOVF    0x24,W
    MOVWF   STATUS
    MOVF    0x23,W
    BCF	    INTCON,0
    RETFIE

LED
    ADDWF   PCL,F
    NOP
    RETLW   0x02	;0000 0010
    RETLW   0x06	;0000 0110
    RETLW   0x0E	;0000 1110
    ; DELAY DE 771uS * 100
DELAY
    MOVLW   .100
    MOVWF   T2
BETA
    MOVLW   .255
    MOVWF   T1
ALFA
    DECFSZ  T1
    GOTO    ALFA
    DECFSZ  T2
    GOTO    BETA
    RETURN
    END