    ; SE DESEA QUE AL APRETAR EL PULSADOR CONECTADO A RA4 PARPADEEN, A UNA FRECUENCIA
    ; DE 0.5HZ, LOS 8 LEDS CONECTADOS EN CATODOS COMUN A LOS 8 TERMINALES DEL PUERTO D
    ; DE UN MICROCONTROLADOR PIC 16F887. DICHO PARPADEO SE DEBE INTERRUMPIR DURANTE
    ; UNOS INSTANTES (3 SEGUNDOS) SE SE APRIETA EL PULSADOR CONECTADO AL TERMINAL RB0.
    ; INICIALMENTE, LOS LEDS ESTAN APAGADOS. EL OSCILADOR ES DE 4MHZ
    
    ; LA INTERRUPCION SE UTILIZA EN EL PUERTO B
    ; SIGUIENDO EL DIAGRAMA NO SE USARA PULL-UP DEL MICRO
    ; PASANDOLE 61D A TMR0 CON EL PREESCALER A 256 PROVOCA UNA INTERRUPCION DE 50mS
    ; ENTONCES PARA 3 SEGUNDOS LE PASO 60 A CONT
    LIST	    P=16F887
    #INCLUDE	    <P16F887.INC>
    
    __CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
    
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    CONT    EQU	    0x20
   
    ORG	    0x00
    GOTO    MAIN
    ORG	    0x04
    GOTO    ISR
    ORG	    0x05
    
MAIN
    
    ; SETEO COMO ENTRADA RB0 Y RA4
    BANKSEL TRISB
    BSF	    TRISB,0
    BSF	    TRISA,4
    CLRF    TRISD
    
    BANKSEL PORTB
    CLRF    PORTB
    CLRF    PORTA
    CLRF    PORTD
    MOVLW   .60
    MOVWF   CONT
    
    MOVLW   0x08
    MOVWF   INTCON
    
    BANKSEL OPTION_REG
    MOVLW   0x07
    MOVWF   OPTION_REG
    
    BANKSEL TMR0
    MOVLW   .61
    MOVWF   TMR0
    
    BTFSC
    
    BSF	    INTCON,7
    
    GOTO    $
    
ISR
    ;SALVO EL CONTEXTO
    MOVWF   0x21
    MOVF    STATUS,W
    MOVWF   0x22
    
    DECFSZ  CONT
    
    ;RECUPERO EL CONTEXTO
    MOVF    0x22,W
    MOVWF   STATUS
    MOVF    0x21,W